// Generated by CoffeeScript 1.9.3
var Card, Card10, Card11, Card12, Card13, Card14, Card15, Card16, Card17, Card18, Card19, Card2, Card20, Card21, Card22, Card23, Card24, Card25, Card26, Card27, Card28, Card29, Card3, Card30, Card31, Card32, Card33, Card34, Card35, Card36, Card4, Card5, Card6, Card7, Card8, Card9, Card99, CardBase,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Card = (function() {
  function Card() {}

  Card.getClass = function(classNum) {
    var res;
    try {
      res = eval("Card" + classNum);
    } catch (_error) {
      return false;
    }
    if (res != null) {
      return false;
    }
    return res;
  };

  return Card;

})();

CardBase = (function() {
  function CardBase() {}

  CardBase.NAME = null;

  CardBase.CATEGORY = null;

  CardBase.DESCRIPTION = null;

  return CardBase;

})();

Card2 = (function(superClass) {
  extend(Card2, superClass);

  function Card2() {
    return Card2.__super__.constructor.apply(this, arguments);
  }

  Card2.NAME = "鉱山";

  return Card2;

})(CardBase);

Card3 = (function(superClass) {
  extend(Card3, superClass);

  function Card3() {
    return Card3.__super__.constructor.apply(this, arguments);
  }

  Card3.NAME = "学校";

  return Card3;

})(CardBase);

Card4 = (function(superClass) {
  extend(Card4, superClass);

  function Card4() {
    return Card4.__super__.constructor.apply(this, arguments);
  }

  Card4.NAME = "大工";

  return Card4;

})(CardBase);

Card5 = (function(superClass) {
  extend(Card5, superClass);

  function Card5() {
    return Card5.__super__.constructor.apply(this, arguments);
  }

  Card5.NAME = "露店";

  return Card5;

})(CardBase);

Card6 = (function(superClass) {
  extend(Card6, superClass);

  function Card6() {
    return Card6.__super__.constructor.apply(this, arguments);
  }

  Card6.NAME = "市場";

  return Card6;

})(CardBase);

Card7 = (function(superClass) {
  extend(Card7, superClass);

  function Card7() {
    return Card7.__super__.constructor.apply(this, arguments);
  }

  Card7.NAME = "高等学校";

  return Card7;

})(CardBase);

Card8 = (function(superClass) {
  extend(Card8, superClass);

  function Card8() {
    return Card8.__super__.constructor.apply(this, arguments);
  }

  Card8.NAME = "スーパーマーケット";

  return Card8;

})(CardBase);

Card9 = (function(superClass) {
  extend(Card9, superClass);

  function Card9() {
    return Card9.__super__.constructor.apply(this, arguments);
  }

  Card9.NAME = "大学";

  return Card9;

})(CardBase);

Card10 = (function(superClass) {
  extend(Card10, superClass);

  function Card10() {
    return Card10.__super__.constructor.apply(this, arguments);
  }

  Card10.NAME = "百貨店";

  return Card10;

})(CardBase);

Card11 = (function(superClass) {
  extend(Card11, superClass);

  function Card11() {
    return Card11.__super__.constructor.apply(this, arguments);
  }

  Card11.NAME = "専門学校";

  return Card11;

})(CardBase);

Card12 = (function(superClass) {
  extend(Card12, superClass);

  function Card12() {
    return Card12.__super__.constructor.apply(this, arguments);
  }

  Card12.NAME = "万博";

  return Card12;

})(CardBase);

Card13 = (function(superClass) {
  extend(Card13, superClass);

  function Card13() {
    return Card13.__super__.constructor.apply(this, arguments);
  }

  Card13.NAME = "農場";

  return Card13;

})(CardBase);

Card14 = (function(superClass) {
  extend(Card14, superClass);

  function Card14() {
    return Card14.__super__.constructor.apply(this, arguments);
  }

  Card14.NAME = "設計事務所";

  return Card14;

})(CardBase);

Card15 = (function(superClass) {
  extend(Card15, superClass);

  function Card15() {
    return Card15.__super__.constructor.apply(this, arguments);
  }

  Card15.NAME = "焼畑";

  return Card15;

})(CardBase);

Card16 = (function(superClass) {
  extend(Card16, superClass);

  function Card16() {
    return Card16.__super__.constructor.apply(this, arguments);
  }

  Card16.NAME = "珈琲店";

  return Card16;

})(CardBase);

Card17 = (function(superClass) {
  extend(Card17, superClass);

  function Card17() {
    return Card17.__super__.constructor.apply(this, arguments);
  }

  Card17.NAME = "工場";

  return Card17;

})(CardBase);

Card18 = (function(superClass) {
  extend(Card18, superClass);

  function Card18() {
    return Card18.__super__.constructor.apply(this, arguments);
  }

  Card18.NAME = "建設会社";

  return Card18;

})(CardBase);

Card19 = (function(superClass) {
  extend(Card19, superClass);

  function Card19() {
    return Card19.__super__.constructor.apply(this, arguments);
  }

  Card19.NAME = "果樹園";

  return Card19;

})(CardBase);

Card20 = (function(superClass) {
  extend(Card20, superClass);

  function Card20() {
    return Card20.__super__.constructor.apply(this, arguments);
  }

  Card20.NAME = "倉庫";

  return Card20;

})(CardBase);

Card21 = (function(superClass) {
  extend(Card21, superClass);

  function Card21() {
    return Card21.__super__.constructor.apply(this, arguments);
  }

  Card21.NAME = "社宅";

  return Card21;

})(CardBase);

Card22 = (function(superClass) {
  extend(Card22, superClass);

  function Card22() {
    return Card22.__super__.constructor.apply(this, arguments);
  }

  Card22.NAME = "法律事務所";

  return Card22;

})(CardBase);

Card23 = (function(superClass) {
  extend(Card23, superClass);

  function Card23() {
    return Card23.__super__.constructor.apply(this, arguments);
  }

  Card23.NAME = "大農園";

  return Card23;

})(CardBase);

Card24 = (function(superClass) {
  extend(Card24, superClass);

  function Card24() {
    return Card24.__super__.constructor.apply(this, arguments);
  }

  Card24.NAME = "レストラン";

  return Card24;

})(CardBase);

Card25 = (function(superClass) {
  extend(Card25, superClass);

  function Card25() {
    return Card25.__super__.constructor.apply(this, arguments);
  }

  Card25.NAME = "開拓民";

  return Card25;

})(CardBase);

Card26 = (function(superClass) {
  extend(Card26, superClass);

  function Card26() {
    return Card26.__super__.constructor.apply(this, arguments);
  }

  Card26.NAME = "不動産屋";

  return Card26;

})(CardBase);

Card27 = (function(superClass) {
  extend(Card27, superClass);

  function Card27() {
    return Card27.__super__.constructor.apply(this, arguments);
  }

  Card27.NAME = "農協";

  return Card27;

})(CardBase);

Card28 = (function(superClass) {
  extend(Card28, superClass);

  function Card28() {
    return Card28.__super__.constructor.apply(this, arguments);
  }

  Card28.NAME = "製鉄所";

  return Card28;

})(CardBase);

Card29 = (function(superClass) {
  extend(Card29, superClass);

  function Card29() {
    return Card29.__super__.constructor.apply(this, arguments);
  }

  Card29.NAME = "ゼネコン";

  return Card29;

})(CardBase);

Card30 = (function(superClass) {
  extend(Card30, superClass);

  function Card30() {
    return Card30.__super__.constructor.apply(this, arguments);
  }

  Card30.NAME = "化学工場";

  return Card30;

})(CardBase);

Card31 = (function(superClass) {
  extend(Card31, superClass);

  function Card31() {
    return Card31.__super__.constructor.apply(this, arguments);
  }

  Card31.NAME = "労働組合";

  return Card31;

})(CardBase);

Card32 = (function(superClass) {
  extend(Card32, superClass);

  function Card32() {
    return Card32.__super__.constructor.apply(this, arguments);
  }

  Card32.NAME = "邸宅";

  return Card32;

})(CardBase);

Card33 = (function(superClass) {
  extend(Card33, superClass);

  function Card33() {
    return Card33.__super__.constructor.apply(this, arguments);
  }

  Card33.NAME = "自動車工場";

  return Card33;

})(CardBase);

Card34 = (function(superClass) {
  extend(Card34, superClass);

  function Card34() {
    return Card34.__super__.constructor.apply(this, arguments);
  }

  Card34.NAME = "邸宅";

  return Card34;

})(CardBase);

Card35 = (function(superClass) {
  extend(Card35, superClass);

  function Card35() {
    return Card35.__super__.constructor.apply(this, arguments);
  }

  Card35.NAME = "鉄道";

  return Card35;

})(CardBase);

Card36 = (function(superClass) {
  extend(Card36, superClass);

  function Card36() {
    return Card36.__super__.constructor.apply(this, arguments);
  }

  Card36.NAME = "本社ビル";

  return Card36;

})(CardBase);

Card99 = (function(superClass) {
  extend(Card99, superClass);

  function Card99() {
    return Card99.__super__.constructor.apply(this, arguments);
  }

  Card99.NAME = "消費財";

  return Card99;

})(CardBase);
