// Generated by CoffeeScript 1.9.3
var CardBase, CardKouzan,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

CardBase = (function() {
  var element, isTap, isWorker;

  element = null;

  isTap = false;

  isWorker = false;

  function CardBase(gameObj, cardNum) {
    this.gameObj = gameObj;
    this.cardNum = cardNum;
  }

  CardBase.prototype.getCardNum = function() {
    return this.cardNum;
  };

  CardBase.prototype.tap = function() {};

  CardBase.prototype.use = function() {};

  CardBase.prototype.movePublic = function() {};

  return CardBase;

})();

CardKouzan = (function(superClass) {
  extend(CardKouzan, superClass);

  function CardKouzan() {
    return CardKouzan.__super__.constructor.apply(this, arguments);
  }

  return CardKouzan;

})(CardBase);
