// Generated by CoffeeScript 1.9.3
var Budget, ButtonCANCEL, ButtonOK, Card, Card10, Card11, Card12, Card13, Card14, Card15, Card16, Card17, Card18, Card19, Card2, Card20, Card21, Card22, Card23, Card24, Card25, Card26, Card27, Card28, Card29, Card3, Card30, Card31, Card32, Card33, Card34, Card35, Card36, Card4, Card5, Card6, Card7, Card8, Card9, Card99, CardBase, Consumer, Deck, HandSpace, LogSpace, Point, PrivateSpace, PublicSpace, RoundDeck, SpaceBase, Stock, Unpaid, Worker,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

SpaceBase = (function() {
  function SpaceBase() {}

  SpaceBase.DIV_ID = null;

  SpaceBase.STATUS_USABLE = 0;

  SpaceBase.STATUS_WORKED = 1;

  SpaceBase.STATUS_DISABLED = 2;

  SpaceBase.IMG_DISABLER = './img/disabler.png';

  SpaceBase.IMG_WORKER = './img/worker.png';

  SpaceBase.init = function() {
    var e;
    e = this.getElement();
    return e.html(this.DIV_ID);
  };

  SpaceBase.getElement = function() {
    return $('#' + this.DIV_ID);
  };

  return SpaceBase;

})();

Budget = (function(superClass) {
  extend(Budget, superClass);

  function Budget() {
    return Budget.__super__.constructor.apply(this, arguments);
  }

  Budget.DIV_ID = 'budget';

  Budget.money = 0;

  Budget.init = function() {
    Budget.__super__.constructor.init.call(this);
    this.money = 0;
    return this.redraw();
  };

  Budget.push = function(amount) {
    if (amount < 0) {
      return false;
    }
    return this.money += amount;
  };

  Budget.pull = function(amount) {
    if (amount < 0) {
      return false;
    }
    if (this.money < amount) {
      return false;
    }
    return this.money -= amount;
  };

  Budget.getAmount = function() {
    return this.money;
  };

  Budget.redraw = function() {
    return this.getElement().html('$ ' + this.getAmount());
  };

  return Budget;

})(SpaceBase);

Card = (function() {
  function Card() {}

  Card.getClass = function(classNum) {
    var res;
    try {
      res = eval("Card" + classNum);
    } catch (_error) {
      return false;
    }
    if (res == null) {
      return false;
    }
    return res;
  };

  return Card;

})();

CardBase = (function() {
  function CardBase() {}

  CardBase.NAME = null;

  CardBase.CATEGORY = null;

  CardBase.DESCRIPTION = null;

  CardBase.COST = 0;

  CardBase.PRICE = 0;

  CardBase.isRightClick = function() {
    return false;
  };

  CardBase.requireCards = function() {
    return [0, 0];
  };

  CardBase.use = function(leftIndexs, rightIndexs) {
    var leftReqNum, ref, rightReqNum;
    if (leftIndexs == null) {
      leftIndexs = [];
    }
    if (rightIndexs == null) {
      rightIndexs = [];
    }
    ref = this.requireCards, leftReqNum = ref[0], rightReqNum = ref[1];
    if (!(leftIndexs.length === leftReqNum && rightReqNum.length === rightReqNum)) {
      return false;
    }
  };

  CardBase.getName = function() {
    return this.NAME;
  };

  CardBase.getCategory = function() {
    return this.CATEGORY;
  };

  CardBase.getNumber = function() {
    var res;
    res = this.name.match(/^Card(\d+)$/);
    if (res != null) {
      return Number(res[1]);
    }
    return false;
  };

  CardBase.getDescription = function() {
    return this.DESCRIPTION;
  };

  CardBase.isPublicOnly = function() {
    return this.CATEGORY === '公共';
  };

  CardBase.isWorkable = function() {
    if (this.CATEGORY === '非職場') {
      return false;
    }
    if (this.CATEGORY === '消費財') {
      return false;
    }
    return true;
  };

  CardBase.isSellable = function() {
    return this.isWorkable();
  };

  CardBase.getCost = function() {
    return this.COST;
  };

  CardBase.getPrice = function() {
    return this.PRICE;
  };

  CardBase.getPoint = function() {
    return this.PRICE * 2;
  };

  CardBase.getImagePath = function() {
    return './img/card/' + this.getNumber() + '.jpg';
  };

  CardBase.getImageObj = function() {
    return $('<img>').attr('src', this.getImagePath());
  };

  return CardBase;

})();

Card2 = (function(superClass) {
  extend(Card2, superClass);

  function Card2() {
    return Card2.__super__.constructor.apply(this, arguments);
  }

  Card2.NAME = "鉱山";

  Card2.CATEGORY = "公共";

  Card2.DESCRIPTION = "カードを1枚引く";

  Card2.use = function() {
    Game.pullDeck();
    return true;
  };

  return Card2;

})(CardBase);

Card3 = (function(superClass) {
  extend(Card3, superClass);

  function Card3() {
    return Card3.__super__.constructor.apply(this, arguments);
  }

  Card3.NAME = "学校";

  Card3.CATEGORY = "公共";

  Card3.DESCRIPTION = "労働者を1人増やす";

  Card3.use = function() {
    Game.addWorkerNum();
    return true;
  };

  return Card3;

})(CardBase);

Card4 = (function(superClass) {
  extend(Card4, superClass);

  function Card4() {
    return Card4.__super__.constructor.apply(this, arguments);
  }

  Card4.NAME = "大工";

  Card4.CATEGORY = "公共";

  Card4.DESCRIPTION = "建物を1つ作る";

  return Card4;

})(CardBase);

Card5 = (function(superClass) {
  extend(Card5, superClass);

  function Card5() {
    return Card5.__super__.constructor.apply(this, arguments);
  }

  Card5.NAME = "露店";

  Card5.CATEGORY = "公共";

  Card5.DESCRIPTION = "手札を1枚捨てる\n家計から$6を得る";

  return Card5;

})(CardBase);

Card6 = (function(superClass) {
  extend(Card6, superClass);

  function Card6() {
    return Card6.__super__.constructor.apply(this, arguments);
  }

  Card6.NAME = "市場";

  Card6.CATEGORY = "公共";

  Card6.DESCRIPTION = "手札を2枚捨てる\n家計から$12を得る";

  return Card6;

})(CardBase);

Card7 = (function(superClass) {
  extend(Card7, superClass);

  function Card7() {
    return Card7.__super__.constructor.apply(this, arguments);
  }

  Card7.NAME = "高等学校";

  Card7.CATEGORY = "公共";

  Card7.DESCRIPTION = "労働者を4人に増やす";

  return Card7;

})(CardBase);

Card8 = (function(superClass) {
  extend(Card8, superClass);

  function Card8() {
    return Card8.__super__.constructor.apply(this, arguments);
  }

  Card8.NAME = "スーパーマーケット";

  Card8.CATEGORY = "公共";

  Card8.DESCRIPTION = "手札を3枚捨てて家計から$18を得る";

  return Card8;

})(CardBase);

Card9 = (function(superClass) {
  extend(Card9, superClass);

  function Card9() {
    return Card9.__super__.constructor.apply(this, arguments);
  }

  Card9.NAME = "大学";

  Card9.CATEGORY = "公共";

  Card9.DESCRIPTION = "労働者を5人に増やす";

  return Card9;

})(CardBase);

Card10 = (function(superClass) {
  extend(Card10, superClass);

  function Card10() {
    return Card10.__super__.constructor.apply(this, arguments);
  }

  Card10.NAME = "百貨店";

  Card10.CATEGORY = "公共";

  Card10.DESCRIPTION = "手札を4枚捨てて家計から$24を得る";

  return Card10;

})(CardBase);

Card11 = (function(superClass) {
  extend(Card11, superClass);

  function Card11() {
    return Card11.__super__.constructor.apply(this, arguments);
  }

  Card11.NAME = "専門学校";

  Card11.CATEGORY = "公共";

  Card11.DESCRIPTION = "労働者を1人増やす\nこのラウンドからすぐ働ける";

  return Card11;

})(CardBase);

Card12 = (function(superClass) {
  extend(Card12, superClass);

  function Card12() {
    return Card12.__super__.constructor.apply(this, arguments);
  }

  Card12.NAME = "万博";

  Card12.CATEGORY = "公共";

  Card12.DESCRIPTION = "手札を5枚捨てて家計から$30を得る";

  return Card12;

})(CardBase);

Card13 = (function(superClass) {
  extend(Card13, superClass);

  function Card13() {
    return Card13.__super__.constructor.apply(this, arguments);
  }

  Card13.NAME = "農場";

  Card13.CATEGORY = "農業";

  Card13.DESCRIPTION = "消費財を2枚引く";

  Card13.COST = 1;

  Card13.PRICE = 3;

  return Card13;

})(CardBase);

Card14 = (function(superClass) {
  extend(Card14, superClass);

  function Card14() {
    return Card14.__super__.constructor.apply(this, arguments);
  }

  Card14.NAME = "設計事務所";

  Card14.DESCRIPTION = "カードを5枚めくり公開する\nうち1枚を引いて残りを捨てる";

  Card14.COST = 1;

  Card14.PRICE = 4;

  return Card14;

})(CardBase);

Card15 = (function(superClass) {
  extend(Card15, superClass);

  function Card15() {
    return Card15.__super__.constructor.apply(this, arguments);
  }

  Card15.NAME = "焼畑";

  Card15.CATEGORY = "農業";

  Card15.DESCRIPTION = "消費財を5枚引く\n焼畑は消滅する";

  Card15.COST = 1;

  Card15.PRICE = 0;

  return Card15;

})(CardBase);

Card16 = (function(superClass) {
  extend(Card16, superClass);

  function Card16() {
    return Card16.__super__.constructor.apply(this, arguments);
  }

  Card16.NAME = "珈琲店";

  Card16.DESCRIPTION = "家計から$5を得る";

  Card16.COST = 1;

  Card16.PRICE = 4;

  return Card16;

})(CardBase);

Card17 = (function(superClass) {
  extend(Card17, superClass);

  function Card17() {
    return Card17.__super__.constructor.apply(this, arguments);
  }

  Card17.NAME = "工場";

  Card17.CATEGORY = "工業";

  Card17.DESCRIPTION = "手札を2枚捨てる\nカードを4枚引く";

  Card17.COST = 2;

  Card17.PRICE = 6;

  return Card17;

})(CardBase);

Card18 = (function(superClass) {
  extend(Card18, superClass);

  function Card18() {
    return Card18.__super__.constructor.apply(this, arguments);
  }

  Card18.NAME = "建設会社";

  Card18.DESCRIPTION = "建物を1つコスト-1で作る\n";

  Card18.COST = 2;

  Card18.PRICE = 5;

  return Card18;

})(CardBase);

Card19 = (function(superClass) {
  extend(Card19, superClass);

  function Card19() {
    return Card19.__super__.constructor.apply(this, arguments);
  }

  Card19.NAME = "果樹園";

  Card19.CATEGORY = "農業";

  Card19.DESCRIPTION = "手札を2枚捨てる\nカードを4枚引く";

  Card19.COST = 2;

  Card19.PRICE = 5;

  return Card19;

})(CardBase);

Card20 = (function(superClass) {
  extend(Card20, superClass);

  function Card20() {
    return Card20.__super__.constructor.apply(this, arguments);
  }

  Card20.NAME = "倉庫";

  Card20.CATEGORY = "非職場";

  Card20.DESCRIPTION = "手札上限+4\n（パッシブ）\n売却不可";

  Card20.COST = 2;

  Card20.PRICE = 5;

  return Card20;

})(CardBase);

Card21 = (function(superClass) {
  extend(Card21, superClass);

  function Card21() {
    return Card21.__super__.constructor.apply(this, arguments);
  }

  Card21.NAME = "社宅";

  Card21.CATEGORY = "非職場";

  Card21.DESCRIPTION = "労働者上限+1\n（パッシブ）\n売却不可";

  Card21.COST = 2;

  Card21.PRICE = 4;

  return Card21;

})(CardBase);

Card22 = (function(superClass) {
  extend(Card22, superClass);

  function Card22() {
    return Card22.__super__.constructor.apply(this, arguments);
  }

  Card22.NAME = "法律事務所";

  Card22.CATEGORY = "非職場";

  Card22.DESCRIPTION = "終了時：負債から5枚まで免除する";

  Card22.COST = 2;

  Card22.PRICE = 4;

  return Card22;

})(CardBase);

Card23 = (function(superClass) {
  extend(Card23, superClass);

  function Card23() {
    return Card23.__super__.constructor.apply(this, arguments);
  }

  Card23.NAME = "大農園";

  Card23.CATEGORY = "農業";

  Card23.DESCRIPTION = "消費財を3枚引く";

  Card23.COST = 3;

  Card23.PRICE = 6;

  return Card23;

})(CardBase);

Card24 = (function(superClass) {
  extend(Card24, superClass);

  function Card24() {
    return Card24.__super__.constructor.apply(this, arguments);
  }

  Card24.NAME = "レストラン";

  Card24.DESCRIPTION = "手札を1枚捨てる\n家計から$15を得る";

  Card24.COST = 3;

  Card24.PRICE = 8;

  return Card24;

})(CardBase);

Card25 = (function(superClass) {
  extend(Card25, superClass);

  function Card25() {
    return Card25.__super__.constructor.apply(this, arguments);
  }

  Card25.NAME = "開拓民";

  Card25.DESCRIPTION = "手札の農業カテゴリの建物を1つコスト0で作る";

  Card25.COST = 3;

  Card25.PRICE = 7;

  return Card25;

})(CardBase);

Card26 = (function(superClass) {
  extend(Card26, superClass);

  function Card26() {
    return Card26.__super__.constructor.apply(this, arguments);
  }

  Card26.NAME = "不動産屋";

  Card26.CATEGORY = "非職場";

  Card26.DESCRIPTION = "終了時：所有する建物1つにつき+3点\n（この建物を含む）\n売却不可";

  Card26.COST = 3;

  Card26.PRICE = 5;

  return Card26;

})(CardBase);

Card27 = (function(superClass) {
  extend(Card27, superClass);

  function Card27() {
    return Card27.__super__.constructor.apply(this, arguments);
  }

  Card27.NAME = "農協";

  Card27.CATEGORY = "非職場";

  Card27.DESCRIPTION = "終了時：手札の消費財1枚につき+3点\n売却不可";

  Card27.COST = 3;

  Card27.PRICE = 6;

  return Card27;

})(CardBase);

Card28 = (function(superClass) {
  extend(Card28, superClass);

  function Card28() {
    return Card28.__super__.constructor.apply(this, arguments);
  }

  Card28.NAME = "製鉄所";

  Card28.CATEGORY = "工業";

  Card28.DESCRIPTION = "カードを3枚引く";

  Card28.COST = 4;

  Card28.PRICE = 10;

  return Card28;

})(CardBase);

Card29 = (function(superClass) {
  extend(Card29, superClass);

  function Card29() {
    return Card29.__super__.constructor.apply(this, arguments);
  }

  Card29.NAME = "ゼネコン";

  Card29.DESCRIPTION = "建物を1つ作る\nカードを2枚引く";

  Card29.COST = 4;

  Card29.PRICE = 9;

  return Card29;

})(CardBase);

Card30 = (function(superClass) {
  extend(Card30, superClass);

  function Card30() {
    return Card30.__super__.constructor.apply(this, arguments);
  }

  Card30.NAME = "化学工場";

  Card30.CATEGORY = "工業";

  Card30.DESCRIPTION = "カードを2枚引く\n手札がなければ4枚引く";

  Card30.COST = 4;

  Card30.PRICE = 9;

  return Card30;

})(CardBase);

Card31 = (function(superClass) {
  extend(Card31, superClass);

  function Card31() {
    return Card31.__super__.constructor.apply(this, arguments);
  }

  Card31.NAME = "労働組合";

  Card31.CATEGORY = "非職場";

  Card31.DESCRIPTION = "終了時：労働者1人につき+6点\n売却不可";

  Card31.COST = 4;

  Card31.PRICE = 0;

  return Card31;

})(CardBase);

Card32 = (function(superClass) {
  extend(Card32, superClass);

  function Card32() {
    return Card32.__super__.constructor.apply(this, arguments);
  }

  Card32.NAME = "邸宅";

  Card32.CATEGORY = "非職場";

  Card32.DESCRIPTION = "売却不可";

  Card32.COST = 4;

  Card32.PRICE = 14;

  return Card32;

})(CardBase);

Card33 = (function(superClass) {
  extend(Card33, superClass);

  function Card33() {
    return Card33.__super__.constructor.apply(this, arguments);
  }

  Card33.NAME = "自動車工場";

  Card33.CATEGORY = "工業";

  Card33.DESCRIPTION = "手札を3枚捨てる\nカードを7枚引く";

  Card33.COST = 5;

  Card33.PRICE = 12;

  return Card33;

})(CardBase);

Card34 = (function(superClass) {
  extend(Card34, superClass);

  function Card34() {
    return Card34.__super__.constructor.apply(this, arguments);
  }

  Card34.NAME = "二胡市建設";

  Card34.DESCRIPTION = "同じコストの建物を2つ作る\n1つ分のコストだけ支払う";

  Card34.COST = 5;

  Card34.PRICE = 10;

  return Card34;

})(CardBase);

Card35 = (function(superClass) {
  extend(Card35, superClass);

  function Card35() {
    return Card35.__super__.constructor.apply(this, arguments);
  }

  Card35.NAME = "鉄道";

  Card35.CATEGORY = "非職場";

  Card35.DESCRIPTION = "終了時：所有する鉱業カテゴリの建物1つにつき+3点\n売却不可";

  Card35.COST = 5;

  Card35.PRICE = 9;

  return Card35;

})(CardBase);

Card36 = (function(superClass) {
  extend(Card36, superClass);

  function Card36() {
    return Card36.__super__.constructor.apply(this, arguments);
  }

  Card36.NAME = "本社ビル";

  Card36.CATEGORY = "非職場";

  Card36.DESCRIPTION = "終了時：所有する非職場カテゴリの建物1つにつき+3点\n売却不可";

  Card36.COST = 5;

  Card36.PRICE = 10;

  return Card36;

})(CardBase);

Card99 = (function(superClass) {
  extend(Card99, superClass);

  function Card99() {
    return Card99.__super__.constructor.apply(this, arguments);
  }

  Card99.NAME = "消費財";

  Card99.CATEGORY = "消費財";

  Card99.DESCRIPTION = "手札やコストとして捨てられる";

  return Card99;

})(CardBase);

Consumer = (function() {
  function Consumer() {}

  Consumer.init = function() {};

  Consumer.pull = function() {
    return 99;
  };

  return Consumer;

})();

Deck = (function() {
  function Deck() {}

  Deck.deck = [];

  Deck.grave = [];

  Deck.init = function() {
    var amount, cardNum, def, i, j, ref;
    this.deck = [];
    def = this.getCardDefine();
    for (cardNum in def) {
      amount = def[cardNum];
      for (i = j = 0, ref = amount; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.deck.push(Number(cardNum));
      }
    }
    this.shuffle();
    return this.grave = [];
  };

  Deck.pull = function() {
    if (this.deck.length === 0) {
      this.recycle();
    }
    return this.deck.shift();
  };

  Deck.place = function(cardNum) {
    return this.deck.unshift(Number(cardNum));
  };

  Deck.trash = function(cardNum) {
    return this.grave.push(Number(cardNum));
  };

  Deck.recycle = function() {
    var cardNum, j, len, ref;
    ref = this.grave;
    for (j = 0, len = ref.length; j < len; j++) {
      cardNum = ref[j];
      this.deck.push(Number(cardNum));
    }
    this.grave = [];
    return this.shuffle();
  };

  Deck.shuffle = function() {
    var copy, i, n;
    copy = [];
    n = this.deck.length;
    while (n) {
      i = Math.floor(Math.random() * n--);
      copy.push(this.deck.splice(i, 1)[0]);
    }
    return this.deck = copy;
  };

  Deck.getCardDefine = function() {
    var res;
    res = {
      13: 7,
      14: 4,
      15: 2,
      16: 2,
      17: 7,
      18: 4,
      19: 3,
      20: 3,
      21: 2,
      22: 1,
      23: 3,
      24: 2,
      25: 2,
      26: 2,
      27: 1,
      28: 3,
      29: 3,
      30: 2,
      31: 1,
      32: 1,
      33: 3,
      34: 2,
      35: 1,
      36: 1
    };
    return res;
  };

  return Deck;

})();

$(function() {
  return Game.init();
});

window.Game = (function() {
  function Game() {}

  Game.objs = {};

  Game.isSetObj = false;

  Game.isClickable = false;

  Game.waitChoice = false;

  Game.isSell = false;

  Game.init = function() {
    var name, obj, ref;
    this.setObj();
    ref = this.objs;
    for (name in ref) {
      obj = ref[name];
      obj.init();
    }
    return this.refresh();
  };

  Game.refresh = function() {
    this.objs["public"].redraw();
    this.objs["private"].redraw();
    this.objs.hand.redraw();
    this.objs.budget.redraw();
    this.objs.stock.redraw();
    this.objs.unpaid.redraw();
    this.objs.point.redraw();
    this.objs.worker.redraw();
    return this.objs.round.redraw();
  };

  Game.setObj = function() {
    if (this.isSetObj) {
      return;
    }
    this.isSetObj = true;
    this.objs["public"] = PublicSpace;
    this.objs["private"] = PrivateSpace;
    this.objs.hand = HandSpace;
    this.objs.log = LogSpace;
    this.objs.round = RoundDeck;
    this.objs.deck = Deck;
    this.objs.consumer = Consumer;
    this.objs.budget = Budget;
    this.objs.stock = Stock;
    this.objs.unpaid = Unpaid;
    this.objs.point = Point;
    this.objs.worker = Worker;
    this.objs.ok = ButtonOK;
    return this.objs.cancel = ButtonCANCEL;
  };

  Game.gameStart = function() {
    this.isClickable = false;
    this.init();
    this.pullDeck(3);
    this.objs.deck.place(17);
    this.pullPublic(4);
    return this.isClickable = true;
  };

  Game.roundEnd = function() {
    var alertStr, minusSalary, penalty;
    minusSalary = this.objs.worker.getTotal() * this.objs.round.getSalary();
    penalty = minusSalary - this.objs.stock.getAmount();
    penalty = penalty > 0 ? penalty : 0;
    alertStr = "ラウンド終了";
    alertStr += "\n\n";
    alertStr += "給料 $" + minusSalary + " を支払います\n";
    if (penalty !== 0) {
      alertStr += "支払えなかった $" + penalty + " が未払いになります";
    }
    alert(alertStr);
    this.objs.stock.pull(minusSalary);
    this.objs.unpaid.push(penalty);
    this.objs.round.addRound();
    this.pullPublic();
    this.objs["public"].resetStatus();
    this.objs["private"].resetStatus();
    this.objs.worker.wake();
    return this.refresh();
  };

  Game.turnEnd = function(kubun, index) {
    var spaceClass;
    spaceClass = this.kubun2class(kubun);
    this.objs.worker.work();
    spaceClass.setWorked(index);
    PublicSpace.disableLastest();
    this.refresh();
    if (this.objs.worker.getActive() <= 0) {
      return this.roundEnd();
    }
  };

  Game.handClickLeft = function(index) {
    if (this.waitChoice === false) {
      return false;
    }
    return this.objs.hand.clickLeft();
  };

  Game.handClickRight = function(index) {
    if (this.waitChoice === false) {
      return false;
    }
    if (this.waitChoice[2] === false) {
      return false;
    }
    return this.objs.hand.clickRight();
  };

  Game.pushOK = function() {
    var _, cardClass, cardIndex, index, j, kubun, left, ref, ref1, res, right, spaceClass;
    if (this.waitChoice === false) {
      return false;
    }
    ref = this.waitChoice, kubun = ref[0], cardIndex = ref[1], _ = ref[2];
    this.waitChoice = false;
    left = [];
    right = [];
    for (index = j = 0, ref1 = this.objs.hand.getAmount(); 0 <= ref1 ? j < ref1 : j > ref1; index = 0 <= ref1 ? ++j : --j) {
      if (this.objs.hand.getSelect() === this.objs.hand.SELECT_LEFT) {
        left.push(index);
      }
      if (this.objs.hand.getSelect() === this.objs.hand.SELECT_RIGHT) {
        right.push(index);
      }
    }
    this.objs.hand.select = [];
    spaceClass = this.kubun2class(kubun);
    cardClass = spaceClass.getCardClass(cardIndex);
    res = cardClass.use(left, right);
    if (res === true) {

    } else {
      alert(res);
      return false;
    }
  };

  Game.pushCANCEL = function() {
    if (this.waitChoice === false) {
      return false;
    }
  };

  Game.work = function(kubun, index) {
    var cardClass, leftReqNum, ref, res, rightReqNum, spaceClass;
    if (!this.isClickable) {
      return false;
    }
    if (!this.kubun2class(kubun).isUsable(index)) {
      return false;
    }
    if (Worker.getActive() <= 0) {
      return false;
    }
    this.isClickable = false;
    spaceClass = this.kubun2class(kubun);
    cardClass = spaceClass.getCardClass(index);
    ref = cardClass.requireCards(), leftReqNum = ref[0], rightReqNum = ref[1];
    if (leftReqNum === 0 && rightReqNum === 0) {
      res = cardClass.use();
      if (res !== true) {
        alert(res);
        this.isClickable = true;
        return false;
      }
      this.turnEnd(kubun, index);
      this.isClickable = true;
    } else {
      this.waitChoice = [kubun, index, cardClass.isRightClick()];
    }
    return true;
  };

  Game.pullDeck = function(amount) {
    var i, j, ref;
    if (amount == null) {
      amount = 1;
    }
    for (i = j = 0, ref = amount; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      this.objs.hand.push(this.objs.deck.pull());
    }
    return this.objs.hand.redraw();
  };

  Game.pullConsumer = function(amount) {
    var i, j, ref;
    if (amount == null) {
      amount = 1;
    }
    for (i = j = 0, ref = amount; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      this.objs.hand.push(this.objs.consumer.pull());
    }
    return this.objs.hand.redraw();
  };

  Game.pullPublic = function(amount) {
    var i, j, ref;
    if (amount == null) {
      amount = 1;
    }
    for (i = j = 0, ref = amount; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      this.objs["public"].push(this.objs.round.pull());
    }
    return this.objs["public"].redraw();
  };

  Game.addWorkerNum = function(amount) {
    var i, j, ref;
    if (amount == null) {
      amount = 1;
    }
    for (i = j = 0, ref = amount; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      this.objs.worker.add();
    }
    return this.objs.worker.redraw();
  };

  Game.addWorkerUntil = function(amount) {
    while (this.objs.worker.getTotal() < amount) {
      this.objs.worker.add();
    }
    return this.objs.worker.redraw();
  };

  Game.addWorkerActiveNum = function(amount) {
    var i, j, ref;
    if (amount == null) {
      amount = 1;
    }
    for (i = j = 0, ref = amount; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      this.objs.worker.add(true);
    }
    return this.objs.worker.redraw();
  };

  Game.getPoint = function() {
    var point, unpaidNum;
    point = 0;
    point += this.objs.stock.getAmount();
    point += this.objs["private"].getPoint();
    unpaidNum = this.objs.unpaid.getAmount();
    if (this.objs["private"].isExistHouritu()) {
      unpaidNum -= 5;
    }
    unpaidNum = unpaidNum < 0 ? 0 : unpaidNum;
    point -= unpaidNum;
    return point;
  };

  Game.kubun2class = function(kubun) {
    if (kubun === "public") {
      return PublicSpace;
    }
    return PrivateSpace;
  };

  return Game;

})();

HandSpace = (function(superClass) {
  extend(HandSpace, superClass);

  function HandSpace() {
    return HandSpace.__super__.constructor.apply(this, arguments);
  }

  HandSpace.DIV_ID = "hand";

  HandSpace.SELECT_NOT = 0;

  HandSpace.SELECT_LEFT = 1;

  HandSpace.SELECT_RIGHT = 2;

  HandSpace.cards = [];

  HandSpace.select = [];

  HandSpace.init = function() {
    HandSpace.__super__.constructor.init.call(this);
    this.cards = [];
    return this.select = [];
  };

  HandSpace.getSelect = function(index) {
    return this.select[index];
  };

  HandSpace.clickLeft = function(index) {
    if (this.select[index] === this.SELECT_LEFT) {
      return this.select[index] = this.SELECT_NOT;
    } else {
      return this.select[index] = this.SELECT_LEFT;
    }
  };

  HandSpace.clickRight = function(index) {
    if (this.select[index] === this.SELECT_RIGHT) {
      return this.select[index] = this.SELECT_NOT;
    } else {
      return this.select[index] = this.SELECT_RIGHT;
    }
  };

  HandSpace.sort = function() {
    var i, j, ref, results;
    this.cards.sort();
    this.select = [];
    results = [];
    for (i = j = 0, ref = this.cards.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      results.push(this.select.push(this.SELECT_NOT));
    }
    return results;
  };

  HandSpace.getAmount = function() {
    return this.cards.length;
  };

  HandSpace.push = function(cardNum) {
    this.cards.push(Number(cardNum));
    return this.select.push(this.SELECT_NOT);
  };

  HandSpace.redraw = function() {
    var e, index, j, me, ref, results;
    me = this.getElement();
    me.html('');
    results = [];
    for (index = j = 0, ref = this.cards.length; 0 <= ref ? j < ref : j > ref; index = 0 <= ref ? ++j : --j) {
      e = this.createElement(index);
      if (e !== false) {
        me.append(e);
      }
      if (this.select[index] === this.SELECT_LEFT) {
        e.addClass("select_left");
      }
      if (this.select[index] === this.SELECT_RIGHT) {
        results.push(e.addClass("select_right"));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  HandSpace.createElement = function(index) {
    var balloonStr, cardClass, cat, catBalloon, catStr, categorySpan, cost, desc, e, header, img, name, point, pointSpan, price;
    if (this.cards[index] == null) {
      return false;
    }
    cardClass = Card.getClass(this.cards[index]);
    name = cardClass.getName();
    cat = cardClass.getCategory();
    cost = cardClass.getCost();
    price = cardClass.getPrice();
    point = cardClass.getPoint();
    desc = cardClass.getDescription();
    e = $('<div>').attr('data-index', index).addClass('hand');
    header = $('<span>').addClass('hand_header').html('[' + cost + ']' + cardClass.getName());
    img = cardClass.getImageObj().addClass('hand_image');
    catStr = cat != null ? '[' + cat + ']' : '';
    categorySpan = $('<span>').addClass('hand_footer hand_category').html(catStr);
    pointSpan = $('<span>').addClass('hand_footer hand_point').html('[$' + point + ']');
    catBalloon = cat != null ? cat : 'なし';
    balloonStr = (desc + "\n--------------------\nカテゴリ：" + catBalloon + "\nコスト：" + cost + "\n売却価格：" + price + "\n得点：" + point).replace(/\n/g, '<br>');
    e.attr('data-tooltip', balloonStr).darkTooltip();
    e.on('click', function() {
      index = $(this).attr('data-index');
      return Game.handClickLeft(index);
    });
    e.on('contextmenu', function() {
      index = $(this).attr('data-index');
      return Game.handClickRight(index);
    });
    e.append(header);
    e.append(img);
    e.append(categorySpan);
    e.append(pointSpan);
    return e;
  };

  return HandSpace;

})(SpaceBase);

LogSpace = (function(superClass) {
  extend(LogSpace, superClass);

  function LogSpace() {
    return LogSpace.__super__.constructor.apply(this, arguments);
  }

  LogSpace.DIV_ID = "log";

  LogSpace.init = function() {
    LogSpace.__super__.constructor.init.call(this);
    return this.clear();
  };

  LogSpace.clear = function() {
    return this.getElement().html('');
  };

  LogSpace.output = function(message) {};

  LogSpace.error = function(message) {};

  LogSpace.fatal = function(message) {};

  return LogSpace;

})(SpaceBase);

Point = (function(superClass) {
  extend(Point, superClass);

  function Point() {
    return Point.__super__.constructor.apply(this, arguments);
  }

  Point.DIV_ID = 'point';

  Point.init = function() {
    return this.redraw(0);
  };

  Point.redraw = function() {
    return this.getElement().html(Game.getPoint());
  };

  return Point;

})(SpaceBase);

PrivateSpace = (function(superClass) {
  extend(PrivateSpace, superClass);

  function PrivateSpace() {
    return PrivateSpace.__super__.constructor.apply(this, arguments);
  }

  PrivateSpace.DIV_ID = "private";

  PrivateSpace.STATUS_USABLE = 0;

  PrivateSpace.STATUS_WORKED = 1;

  PrivateSpace.cards = [];

  PrivateSpace.status = [];

  PrivateSpace.init = function() {
    PrivateSpace.__super__.constructor.init.call(this);
    this.cards = [];
    return this.status = [];
  };

  PrivateSpace.resetStatus = function() {
    var index, j, ref, results;
    results = [];
    for (index = j = 0, ref = this.cards.length; 0 <= ref ? j < ref : j > ref; index = 0 <= ref ? ++j : --j) {
      results.push(this.status[index] = this.STATUS_USABLE);
    }
    return results;
  };

  PrivateSpace.getCardClass = function(index) {
    return Card.getClass(this.cards[index]);
  };

  PrivateSpace.isUsable = function(index) {
    if (this.status[index] == null) {
      return false;
    }
    if (this.status[index] !== this.STATUS_USABLE) {
      return false;
    }
    if (!this.getCardClass(index).isWorkable()) {
      return false;
    }
    return true;
  };

  PrivateSpace.getPoint = function() {
    var c, cardClass, j, len, point, ref;
    point = 0;
    ref = this.cards;
    for (j = 0, len = ref.length; j < len; j++) {
      c = ref[j];
      cardClass = Card.getClass(c);
      point += cardClass.getPoint();
    }
    return point;
  };

  PrivateSpace.push = function(cardNum) {
    this.cards.push(Number(cardNum));
    return this.status.push(this.STATUS_USABLE);
  };

  PrivateSpace.redraw = function() {
    var e, index, j, me, ref, results;
    me = this.getElement();
    me.html('');
    results = [];
    for (index = j = 0, ref = this.cards.length; 0 <= ref ? j < ref : j > ref; index = 0 <= ref ? ++j : --j) {
      e = this.createElement(index);
      if (e !== false) {
        results.push(me.append(e));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  PrivateSpace.createElement = function(index) {
    var balloonStr, cardClass, cat, catBalloon, catStr, categorySpan, cost, costStr, desc, e, header, img, name, point, pointSpan, pointStr, price;
    if (this.cards[index] == null) {
      return false;
    }
    cardClass = this.getCardClass(index);
    name = cardClass.getName();
    cat = cardClass.getCategory();
    cost = cardClass.getCost();
    price = cardClass.getPrice();
    point = cardClass.getPoint();
    desc = cardClass.getDescription();
    e = $('<div>').attr('data-index', index).addClass('private');
    costStr = cardClass.isPublicOnly() ? '' : '[' + cost + ']';
    header = $('<span>').addClass('private_header').html(costStr + cardClass.getName());
    img = cardClass.getImageObj().addClass('private_image');
    catStr = cat != null ? '[' + cat + ']' : '';
    categorySpan = $('<span>').addClass('private_footer private_category').html(catStr);
    pointStr = cardClass.isPublicOnly() ? '' : '[$' + point + ']';
    pointSpan = $('<span>').addClass('private_footer private_point').html(pointStr);
    catBalloon = cat != null ? cat : 'なし';
    balloonStr = (desc + "\n--------------------\nカテゴリ：" + catBalloon + "\nコスト：" + cost + "\n売却価格：" + price + "\n得点：" + point).replace(/\n/g, '<br>');
    e.attr('data-tooltip', balloonStr).darkTooltip();
    switch (this.status[index]) {
      case this.STATUS_WORKED:
        e.append($('<img>').attr('src', this.IMG_WORKER).addClass('worker'));
        break;
      case this.STATUS_TIMER:
        e.append($('<img>').attr('src', this.IMG_TIMER).addClass('worker'));
    }
    e.dblclick(function() {
      index = Number($(this).attr('data-index'));
      return Game.work('private', index);
    });
    e.append(header);
    e.append(img);
    e.append(categorySpan);
    e.append(pointSpan);
    return e;
  };

  PrivateSpace.isExistHouritu = function() {
    var cardNum, j, len, ref;
    ref = this.cards;
    for (j = 0, len = ref.length; j < len; j++) {
      cardNum = ref[j];
      if (cardNum === 22) {
        return true;
      }
    }
    return false;
  };

  return PrivateSpace;

})(SpaceBase);

PublicSpace = (function(superClass) {
  extend(PublicSpace, superClass);

  function PublicSpace() {
    return PublicSpace.__super__.constructor.apply(this, arguments);
  }

  PublicSpace.DIV_ID = "public";

  PublicSpace.cards = [];

  PublicSpace.status = [];

  PublicSpace.init = function() {
    PublicSpace.__super__.constructor.init.call(this);
    this.cards = [];
    return this.status = [];
  };

  PublicSpace.resetStatus = function() {
    var index, j, ref, results;
    results = [];
    for (index = j = 0, ref = this.cards.length; 0 <= ref ? j < ref : j > ref; index = 0 <= ref ? ++j : --j) {
      results.push(this.status[index] = this.STATUS_USABLE);
    }
    return results;
  };

  PublicSpace.getCardClass = function(index) {
    return Card.getClass(this.cards[index]);
  };

  PublicSpace.isUsable = function(index) {
    if (this.status[index] == null) {
      return false;
    }
    if (this.status[index] !== this.STATUS_USABLE) {
      return false;
    }
    return true;
  };

  PublicSpace.setWorked = function(index) {
    if (this.isUsable(index === false)) {
      return false;
    }
    return this.status[index] = this.STATUS_WORKED;
  };

  PublicSpace.setDisabled = function(index) {
    if (this.isUsable(index === false)) {
      return false;
    }
    return this.status[index] = this.STATUS_DISABLED;
  };

  PublicSpace.push = function(cardNum) {
    this.cards.push(Number(cardNum));
    return this.status.push(this.STATUS_USABLE);
  };

  PublicSpace.disableLastest = function() {
    var index, j, ref, results;
    results = [];
    for (index = j = ref = this.status.length - 1; ref <= 0 ? j <= 0 : j >= 0; index = ref <= 0 ? ++j : --j) {
      if (this.status[index] === this.STATUS_USABLE) {
        this.status[index] = this.STATUS_DISABLED;
        break;
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  PublicSpace.redraw = function() {
    var e, index, j, me, ref, results;
    me = this.getElement();
    me.html('');
    results = [];
    for (index = j = 0, ref = this.cards.length; 0 <= ref ? j < ref : j > ref; index = 0 <= ref ? ++j : --j) {
      e = this.createElement(index);
      if (e !== false) {
        results.push(me.append(e));
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  PublicSpace.createElement = function(index) {
    var balloonStr, cardClass, cat, catBalloon, catStr, categorySpan, cost, costBalloon, costStr, desc, e, header, img, name, point, pointBalloon, pointSpan, pointStr, price, priceBalloon;
    if (this.cards[index] == null) {
      return false;
    }
    cardClass = this.getCardClass(index);
    name = cardClass.getName();
    cat = cardClass.getCategory();
    cost = cardClass.getCost();
    price = cardClass.getPrice();
    point = cardClass.getPoint();
    desc = cardClass.getDescription();
    e = $('<div>').attr('data-index', index).addClass('public');
    costStr = cardClass.isPublicOnly() ? '' : '[' + cost + ']';
    header = $('<span>').addClass('public_header').html(costStr + cardClass.getName());
    img = cardClass.getImageObj().addClass('public_image');
    catStr = cat != null ? '[' + cat + ']' : '';
    categorySpan = $('<span>').addClass('public_footer public_category').html(catStr);
    pointStr = cardClass.isPublicOnly() ? '' : '[$' + point + ']';
    pointSpan = $('<span>').addClass('public_footer public_point').html(pointStr);
    costBalloon = cardClass.isPublicOnly() ? '-' : cost;
    priceBalloon = cardClass.isPublicOnly() ? '-' : price;
    pointBalloon = cardClass.isPublicOnly() ? '-' : point;
    catBalloon = cat != null ? cat : 'なし';
    balloonStr = (desc + "\n--------------------\nカテゴリ：" + catBalloon + "\nコスト：" + costBalloon + "\n売却価格：" + priceBalloon + "\n得点：" + pointBalloon).replace(/\n/g, '<br>');
    e.attr('data-tooltip', balloonStr).darkTooltip({
      gravity: 'north'
    });
    switch (this.status[index]) {
      case this.STATUS_WORKED:
        e.addClass('used');
        e.append($('<img>').attr('src', this.IMG_WORKER).addClass('worker'));
        break;
      case this.STATUS_DISABLED:
        e.addClass('used');
        e.append($('<img>').attr('src', this.IMG_DISABLER).addClass('worker'));
    }
    e.dblclick(function() {
      index = Number($(this).attr('data-index'));
      return Game.work('public', index);
    });
    e.append(header);
    e.append(img);
    e.append(categorySpan);
    e.append(pointSpan);
    return e;
  };

  return PublicSpace;

})(SpaceBase);

RoundDeck = (function(superClass) {
  extend(RoundDeck, superClass);

  function RoundDeck() {
    return RoundDeck.__super__.constructor.apply(this, arguments);
  }

  RoundDeck.DIV_ID = 'round';

  RoundDeck.ROUND_MAP = {
    1: 2,
    2: 2,
    3: 3,
    4: 3,
    5: 3,
    6: 4,
    7: 4,
    8: 5,
    9: 5,
    10: 0
  };

  RoundDeck.deck = [];

  RoundDeck.round = 0;

  RoundDeck.init = function() {
    this.deck = [2, 3, 4, 13, 5, 6, 7, 8, 9, 10, 11, 12];
    return this.round = 1;
  };

  RoundDeck.pull = function() {
    if (this.deck.length === 0) {
      false;
    }
    return this.deck.shift();
  };

  RoundDeck.getRound = function() {
    return this.round;
  };

  RoundDeck.getSalary = function() {
    return this.ROUND_MAP[this.getRound()];
  };

  RoundDeck.addRound = function() {
    return this.round++;
  };

  RoundDeck.isGameEnd = function() {
    return this.round > 9;
  };

  RoundDeck.redraw = function() {
    return this.getElement().html('' + this.getRound() + ' / $' + this.getSalary());
  };

  return RoundDeck;

})(SpaceBase);

Stock = (function(superClass) {
  extend(Stock, superClass);

  function Stock() {
    return Stock.__super__.constructor.apply(this, arguments);
  }

  Stock.DIV_ID = 'stock';

  Stock.money = 5;

  Stock.init = function() {
    Stock.__super__.constructor.init.call(this);
    this.money = 5;
    return this.redraw();
  };

  Stock.push = function(amount) {
    if (amount < 0) {
      return false;
    }
    return this.money += amount;
  };

  Stock.pull = function(amount) {
    if (amount < 0) {
      return false;
    }
    this.money -= amount;
    return this.money = this.money < 0 ? 0 : this.money;
  };

  Stock.getAmount = function() {
    return this.money;
  };

  Stock.redraw = function() {
    return this.getElement().html('$ ' + this.getAmount());
  };

  return Stock;

})(SpaceBase);

Unpaid = (function(superClass) {
  extend(Unpaid, superClass);

  function Unpaid() {
    return Unpaid.__super__.constructor.apply(this, arguments);
  }

  Unpaid.DIV_ID = 'unpaid';

  Unpaid.money = 0;

  Unpaid.init = function() {
    Unpaid.__super__.constructor.init.call(this);
    this.money = 0;
    return this.redraw();
  };

  Unpaid.push = function(amount) {
    if (amount < 0) {
      return false;
    }
    return this.money += amount;
  };

  Unpaid.getAmount = function() {
    return this.money;
  };

  Unpaid.redraw = function() {
    return this.getElement().html('$ ' + this.getAmount());
  };

  return Unpaid;

})(SpaceBase);

Worker = (function(superClass) {
  extend(Worker, superClass);

  function Worker() {
    return Worker.__super__.constructor.apply(this, arguments);
  }

  Worker.DIV_ID = 'worker';

  Worker.active = 0;

  Worker.max = 0;

  Worker.init = function() {
    Worker.__super__.constructor.init.call(this);
    this.active = 2;
    this.max = 2;
    return this.redraw();
  };

  Worker.getTotal = function() {
    return this.max;
  };

  Worker.getActive = function() {
    return this.active;
  };

  Worker.add = function(isActiveNow) {
    if (isActiveNow == null) {
      isActiveNow = false;
    }
    this.max++;
    if (isActiveNow) {
      this.active++;
    }
    return this.redraw();
  };

  Worker.wake = function() {
    this.active = this.max;
    return this.redraw();
  };

  Worker.work = function() {
    if (this.active <= 0) {
      return false;
    }
    this.active--;
    return this.redraw();
  };

  Worker.redraw = function() {
    return this.getElement().html('' + this.active + ' / ' + this.max);
  };

  return Worker;

})(SpaceBase);

ButtonOK = (function(superClass) {
  extend(ButtonOK, superClass);

  function ButtonOK() {
    return ButtonOK.__super__.constructor.apply(this, arguments);
  }

  ButtonOK.DIV_ID = 'ok';

  ButtonOK.init = function() {
    this.disable();
    return this.getElement().on('click', function() {
      return Game.pushOK();
    });
  };

  ButtonOK.enable = function() {
    return this.getElement().prop("disabled", false).removeClass("disabled");
  };

  ButtonOK.disable = function() {
    return this.getElement().prop("disabled", true).addClass("disabled");
  };

  return ButtonOK;

})(SpaceBase);

ButtonCANCEL = (function(superClass) {
  extend(ButtonCANCEL, superClass);

  function ButtonCANCEL() {
    return ButtonCANCEL.__super__.constructor.apply(this, arguments);
  }

  ButtonCANCEL.DIV_ID = 'cancel';

  ButtonCANCEL.init = function() {
    this.disable();
    return this.getElement().on('click', function() {
      return Game.pushCANCEL();
    });
  };

  ButtonCANCEL.enable = function() {
    return this.getElement().prop("disabled", false).removeClass("disabled");
  };

  ButtonCANCEL.disable = function() {
    return this.getElement().prop("disabled", true).addClass("disabled");
  };

  return ButtonCANCEL;

})(SpaceBase);
