// Generated by CoffeeScript 1.9.3
var Budget, Consumer, Deck, HandSpace, LogSpace, PrivateSpace, PublicSpace, RoundDeck, SpaceBase,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.Game = (function() {
  function Game() {}

  Game.objs = {};

  Game.isSetObj = false;

  Game.init = function() {
    var name, obj, ref, results;
    this.setObj();
    ref = this.objs;
    results = [];
    for (name in ref) {
      obj = ref[name];
      results.push(obj.init());
    }
    return results;
  };

  Game.setObj = function() {
    if (this.isSetObj) {
      return;
    }
    this.isSetObj = true;
    this.objs["public"] = PublicSpace;
    this.objs["private"] = PrivateSpace;
    this.objs.hand = HandSpace;
    this.objs.log = LogSpace;
    this.objs.budget = Budget;
    this.objs.round = RoundDeck;
    this.objs.deck = Deck;
    return this.objs.consumer = Consumer;
  };

  Game.pull2hand = function(amount) {
    var i, j, ref, results;
    if (amount == null) {
      amount = 1;
    }
    results = [];
    for (i = j = 0, ref = amount; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      results.push(this.objs.hand.push(this.objs.deck.pull()));
    }
    return results;
  };

  return Game;

})();

SpaceBase = (function() {
  function SpaceBase() {}

  SpaceBase.DIV_ID = null;

  SpaceBase.init = function() {
    var e;
    e = this.getElement();
    return e.html(this.DIV_ID);
  };

  SpaceBase.getElement = function() {
    return $('#' + this.DIV_ID);
  };

  return SpaceBase;

})();

PublicSpace = (function(superClass) {
  extend(PublicSpace, superClass);

  function PublicSpace() {
    return PublicSpace.__super__.constructor.apply(this, arguments);
  }

  PublicSpace.DIV_ID = "public";

  PublicSpace.cards = [];

  PublicSpace.init = function() {
    PublicSpace.__super__.constructor.init.call(this);
    return this.cards = {};
  };

  PublicSpace.insert = function(cardObj) {};

  return PublicSpace;

})(SpaceBase);

PrivateSpace = (function(superClass) {
  extend(PrivateSpace, superClass);

  function PrivateSpace() {
    return PrivateSpace.__super__.constructor.apply(this, arguments);
  }

  PrivateSpace.DIV_ID = "private";

  PrivateSpace.cards = [];

  PrivateSpace.init = function() {
    return PrivateSpace.__super__.constructor.init.call(this);
  };

  return PrivateSpace;

})(SpaceBase);

LogSpace = (function(superClass) {
  extend(LogSpace, superClass);

  function LogSpace() {
    return LogSpace.__super__.constructor.apply(this, arguments);
  }

  LogSpace.DIV_ID = "log";

  LogSpace.init = function() {
    return LogSpace.__super__.constructor.init.call(this);
  };

  LogSpace.clear = function() {
    return this.getElement().html('');
  };

  LogSpace.output = function(message) {};

  LogSpace.error = function(message) {};

  LogSpace.fatal = function(message) {};

  return LogSpace;

})(SpaceBase);

HandSpace = (function(superClass) {
  extend(HandSpace, superClass);

  function HandSpace() {
    return HandSpace.__super__.constructor.apply(this, arguments);
  }

  HandSpace.DIV_ID = "hand";

  HandSpace.cards = [];

  HandSpace.init = function() {
    return HandSpace.__super__.constructor.init.call(this);
  };

  HandSpace.sort = function() {
    return this.cards.sort();
  };

  HandSpace.push = function(cardNum) {
    this.cards.push(cardNum);
    this.sort();
    return this.redraw();
  };

  HandSpace.redraw = function() {
    var index, j, me, ref, results;
    me = this.getElement();
    me.html('');
    results = [];
    for (index = j = 0, ref = this.cards.length; 0 <= ref ? j < ref : j > ref; index = 0 <= ref ? ++j : --j) {
      results.push(me.append(this.createElement(index)));
    }
    return results;
  };

  HandSpace.createElement = function(index) {
    var cardClass, e, img, title;
    if (this.cards[index] == null) {
      return false;
    }
    cardClass = Card.getClass(this.cards[index]);
    e = $('<div>').addClass('hand');
    title = $('<span>').addClass('hand_title').html(cardClass.getName());
    img = cardClass.getImageObj().addClass('hand_image');
    e.append(img);
    e.append(title);
    return e;
  };

  return HandSpace;

})(SpaceBase);

RoundDeck = (function() {
  function RoundDeck() {}

  RoundDeck.deck = [];

  RoundDeck.init = function() {
    return this.deck = [5, 6, 7, 8, 9, 10, 11, 12];
  };

  RoundDeck.pull = function() {
    if (this.deck.length === 0) {
      false;
    }
    return this.deck.shift();
  };

  return RoundDeck;

})();

Deck = (function() {
  function Deck() {}

  Deck.deck = [];

  Deck.grave = [];

  Deck.init = function() {
    var amount, cardNum, def, i, j, ref;
    this.deck = [];
    def = this.getCardDefine();
    for (cardNum in def) {
      amount = def[cardNum];
      for (i = j = 0, ref = amount; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        this.deck.push(cardNum);
      }
    }
    this.shuffle();
    return this.grave = [];
  };

  Deck.pull = function() {
    if (this.deck.length === 0) {
      this.recycle();
    }
    return this.deck.pop();
  };

  Deck.trash = function(cardNum) {
    return this.grave.push(cardNum);
  };

  Deck.recycle = function() {
    var cardNum, j, len, ref;
    ref = this.grave;
    for (j = 0, len = ref.length; j < len; j++) {
      cardNum = ref[j];
      this.deck.push(cardNum);
    }
    this.grave = [];
    return this.shuffle();
  };

  Deck.shuffle = function() {
    var copy, i, n;
    copy = [];
    n = this.deck.length;
    while (n) {
      i = Math.floor(Math.random() * n--);
      copy.push(this.deck.splice(i, 1)[0]);
    }
    return this.deck = copy;
  };

  Deck.getCardDefine = function() {
    var res;
    res = {
      13: 8,
      14: 4,
      15: 2,
      16: 2,
      17: 8,
      18: 4,
      19: 3,
      20: 3,
      21: 2,
      22: 1,
      23: 3,
      24: 2,
      25: 2,
      26: 2,
      27: 1,
      28: 3,
      29: 3,
      30: 2,
      31: 1,
      32: 1,
      33: 3,
      34: 2,
      35: 1,
      36: 1
    };
    return res;
  };

  return Deck;

})();

Consumer = (function() {
  function Consumer() {}

  Consumer.init = function() {};

  Consumer.pull = function() {
    return 99;
  };

  return Consumer;

})();

Budget = (function() {
  function Budget() {}

  Budget.money = 0;

  Budget.init = function() {
    return this.money = 0;
  };

  Budget.push = function(amount) {
    if (amount < 0) {
      return false;
    }
    return this.money += amount;
  };

  Budget.pull = function(amount) {
    if (amount < 0) {
      return false;
    }
    if (this.money < amount) {
      return false;
    }
    return this.money -= amount;
  };

  Budget.getAmount = function() {
    return this.money;
  };

  return Budget;

})();
